namespace: atproto
environment: production
plc_url: https://plc.directory
db_user: kingyosun
db_name: atproto-postgresql
db_storage_capacity: 300Gi
db_hostPath: /data/atproto-postgres
pds_imageRepo: docker.io/kingyosun/atproto_k8s
pds_imageTag: latest
pds_url: http://localhost:3000/
pds_host_domain: localhost:3000
pds-blobs_hostPath: /media/kingyosun/storage/atproto-pds-blobs
pds-blobs_storage_capacity: 3000Gi
pds-blobs-tmp_hostPath: /data/atproto-pds-blobs-tmp
pds-blobs-tmp_storage_capacity: 100Gi
pds-blobs-cache_hostPath: /data/atproto-pds-blobs-cache
pds-blobs-cache_storage_capacity: 100Gi
pds_blobstore_loc: /blobstore
pds_blobstore_tmp: /blobstore_tmp
pds_blob_cache_loc: /blob_cache
pds_version: 0.0.0
pds_invite_required: true
pds_user_invite_interval: 604800000
pds_log_level: info
db_pass: NeedOverride
cloudflared_token: NeedOverride
pds_jwt_secret: NeedOverride
pds_admin_password: NeedOverride
pds_repo_signing_key: NeedOverride
pds_recovery_key: NeedOverride
pds_plc_rotation_key: NeedOverride
pds_moderator_password: NeedOverride
pds_smtp_host: NeedOverride
pds_smtp_username: NeedOverride
pds_smtp_password: NeedOverride
pds_email_smtp_url: NeedOverride
pds_no_reply_address: NeedOverride
pds_available_user_domains: NeedOverride
pds_server_did: NeedOverride
pds_labeler_did: NeedOverride
