apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atproto.fullname" . }}-env
  namespace: {{ .Values.namespace }}
data:
  BLOBSTORE_LOC: {{ .Values.pds_blobstore_loc }}
  BLOBSTORE_TMP: {{ .Values.pds_blobstore_tmp }}
  BLOB_CACHE_LOC: {{ .Values.pds_blob_cache_loc }}
  PUBLIC_URL: {{ .Values.pds_url }}
  DB_CREDS_JSON: '{"username":"{{ .Values.db_user }}","password":"{{ .Values.db_pass }}","host":"{{ include "atproto.fullname" . }}-postgres.{{ .Values.namespace }}.svc.cluster.local","port":"5432"}'
  DB_MIGRATE_CREDS_JSON: '{"username":"{{ .Values.db_user }}","password":"{{ .Values.db_pass }}","host":"{{ include "atproto.fullname" . }}-postgres.{{ .Values.namespace }}.svc.cluster.local","port":"5432"}'
  DB_POSTGRES_URL: postgresql://{{ include "atproto.fullname" . }}-postgres.{{ .Values.namespace }}.svc.cluster.local:5432/postgres?user={{ .Values.db_user }}&password={{ .Values.db_pass }}
  SMTP_HOST: {{ .Values.pds_smtp_host }}
  SMTP_USERNAME: {{ .Values.pds_smtp_username }}
  EMAIL_SMTP_URL: {{ .Values.pds_email_smtp_url }}
  EMAIL_NO_REPLY_ADDRESS: {{ .Values.pds_no_reply_address }}
  PDS_VERSION: {{ .Values.pds_version }}
  DID_PLC_URL: {{ .Values.plc_url }}
  INVITE_REQUIRED: {{ .Values.pds_invite_required }}
  USER_INVITE_INTERVAL: {{ .Values.pds_user_invite_interval }}
  AVAILABLE_USER_DOMAINS: {{ .Values.pds_available_user_domains }}
  LOG_ENABLED: "true"
  LOG_LEVEL: {{ .Values.pds_log_level }}
  SERVER_DID: {{ .Values.pds_server_did }}
  LABELER_DID: {{ .Values.pds_labeler_did }}
  TLS: "1"
  HOSTNAME: {{ .Values.pds_host_domain }}
  DB_POOL_SIZE: "{{ .Values.pds_db_pool_size }}"
  DB_POOL_MAX_USES: "{{ .Values.pds_db_pool_max_uses }}"
  DB_POOL_IDLE_TIMEOUT_MS: "{{ .Values.pds_pool_idle_timeout_ms }}""
