apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atproto.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels: {{- include "atproto-postgres.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "atproto-postgres.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels: {{- include "atproto-postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: postgres:14.6-alpine
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db_user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db_pass }}
            - name: POSTGRES_DB
              value: {{ .Values.db_name }}
          ports:
            - containerPort: 5432
          args: ['-c', 'log_statement=ddl', '-c', 'log_destination=stderr']
          volumeMounts:
            - name: atproto-postgresql-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: atproto-postgresql-pvc
          persistentVolumeClaim:
            claimName: atproto-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atproto.fullname" . }}-postgres
  labels: {{- include "atproto-postgres.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    {{- include "atproto-postgres.selectorLabels" . | nindent 4 }}
