apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atproto.fullname" . }}-bsky-env-secret
stringData:
  ADMIN_PASSWORD: {{ .Values.pds_admin_password }}
  MODERATOR_PASSWORD: {{ .Values.pds_moderator_password }}
  TRIAGE_PASSWORD: {{ .Values.pds_triage_password }}

